name: CI-CD

on:
  push:
    branches:
      - develop  # develop 브랜치에 push될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Docker Buildx 환경 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. docker image 빌드
      - name: Build docker image
        run: |
          docker build -t leafmapadmin/leafmap-deploy:latest .

      # 4. docker hub에 로그인
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. docker image 푸시
      - name: Push Docker image to registry
        run: |
          docker push leafmapadmin/leafmap-deploy:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build # build job 이후 deploy job
    steps:
      # 1. SSH to EC2 and Deploy to EC2
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |  # EC2에서 기존 컨테이너를 중지하고 새로운 이미지를 실행함
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull leafmapadmin/leafmap-deploy:latest  
            docker stop leafmap-container || true  
            docker rm leafmap-container || true  
            docker run --env-file /home/ec2-user/leafmap-deploy/.env -d -p 8080:8080 --name leafmap-container leafmapadmin/leafmap-deploy:latest
